### ISSUE TITLE
.github repository name prevent synchronization with GitLab

### ISSUE THREAD

**Issue by amottier** [centreon/.github#2]
As Centreon is member of [OW2](https://www.ow2.org/view/Membership_Joining/Members_Updated#Centreon), we setup (for source code archiving purpose) a synchronization between Centreon organization on GitHub and a [centreon group on OW2 GitLab](https://gitlab.ow2.org/centreon).  
Sadly [GitLab does not accept](https://docs.gitlab.com/ee/user/reserved_names.html#limitations-on-project-and-group-names) a dot at the start of project name. And also the tool we are using for synchronization ([Git Mirror](https://github.com/bachp/git-mirror)) does not allow to exclude a repository from an organization synchronization.  

So I was wondering if renaming this project (`.github`) to use a name that would fit GitLab requirement would be doable? Thanks.

**Comment by sc979** [comment]
Dear @amottier ,

This is a special Github repository, intended to centralize specific templates such as issue or pull request template.
The file available in this repository will be available by default in all the repositories in the organisation.
What is why it is not possible to remote the dot in the repository name, just as it is not necessary to synchronize it.

More details are available in following article: https://www.freecodecamp.org/news/how-to-use-the-dot-github-repository/

**Comment by amottier** [comment]
Thanks a lot for the feedback, and I agree that it is not key to synchronize such repository so I'll adjust the settings on our side.
